name: notebooks2
channels:
  - conda-forge
  - conda 
  - pytorch
  - pypi
dependencies:
  - r-essentials
  - r-tensorflow
  - r-keras
  - r-boot
  - r-caret
  - r-learnr
  - r-rstan
  - r-brms
  - r-mlr
  - r-superlearner
  - r-cairo
  - r-forecast
  - r-autoshiny
  - r-acepack
  - r-rjava
  - r-leaps
  - r-regnet
  - r-aspect
  - r-sem 
  - r-polycor
  - r-ggvis
  - r-relimp
  - r-sparklyr
  - r-sparkr
  - r-sparsemvn
  - r-sparsesem
  - r-sparsesvd
  - r-sparsesvm
  - r-clustergeneration
  - r-sautomata
  - r-arules
  - r-arulescba
  - r-arulessequences
  - r-cloudml
  - r-dbplyr
  - r-domino
  - r-fastrweb
  - r-h2o
  - r-leaps
  - r-onnx
  - r-plumber
  - r-pmml
  - r-pmmltransformations
  - r-rserve
  - r-sparklyr
  - r-sparkr
  - r-tidytext
  - r-tidyselect
  - r-tidyverse
  - r-tilting
  - r-xgboost
  - r-bnlearn
  - r-bnclassify
  - r-bnn
  - r-boolnet
  - r-ggm
  - r-ggmridge
  - r-ggmselect
  - r-xgobi
  - r-xml
  - r-mgcv
  - r-yhatr
  - libgcc
  - gxx_linux-64
  - python                          
  - pip
  - pandas-profiling
  - plotly
  - jupyterlab-plotly-extension
  - rpy2                         
  - rsa                           
  - scikit-image                  
  - scikit-learn 
  - sklearn-pandas        
  - dask
  - pandas-datareader             
  - pandas-gbq                    
  - pandocfilters 
  - tensorboard                   
  - tensorboard-plugin-wit        
  - tensorflow                    
  - tensorflow-datasets           
  - tensorflow-estimator          
  - tensorflow-hub                
  - tensorflow-metadata           
  - tensorflow-probability        
  - torchtext                     
  - torchvision                   
  - tornado   
  - Keras                         
  - Keras-Preprocessing           
  - matplotlib                    
  - matplotlib-venn
  - plotly
  - pycountry
  - scipy                         
  - scs                           
  - seaborn
  - statsmodels==0.12.1
  - nbconvert                     
  - nbformat                      
  - nest-asyncio                  
  - networkx                      
  - nibabel                       
  - nltk                          
  - notebook                      
  - numba                         
  - numexpr                       
  - numpy                         
  - oauth2client                  
  - oauthlib      
  - pytorch